#!/usr/bin/env bash

# Install, update and run wrapper for chattarina.py
# Assumes the user has a ~/.local/bin in $PATH to run from.

repo="https://github.com/basebelong/chattarina.git"
# Install - will prompt for API key
if [[ $1 == "-i" ]] || [[ $1 == "--install" ]]; then
	mkdir -p ~/.local/opt
    mkdir -p ~/.local/bin
	cd ~/.local/opt
	git clone "${repo} \
		|| { echo "Error cloning repo"; exit 1; }

	if ! [ -f ~/.local/opt/chattarina/.env ]; then
		touch ~/.local/opt/chattarina/.env
		echo -n "Enter your OpenAI API key for ChatGPT: "
		read openai_api_key
		echo "OPENAI_API_KEY=${openai_api_key}" > ~/.local/opt/chattarina/.env
	fi

    cp ~/.local/opt/chattarina/chattarina ~/.local/bin/chattarina

	cd ~/.local/opt/chattarina
	# Better to have all deps in a venv
	if ! [ -d venv ]; then
		python3 -m venv venv
	fi
	source venv/bin/activate \
		&& pip install -r requirements.txt
	exit
fi

# Updates by git pull.
if [[ $1 == "-u" ]] || [[ $1 == "--update" ]]; then
	cd ~/.local/opt/chattarina
	git pull \
		&& echo "Latest version" \
		|| echo "Error updating"
	exit
fi

cd ~/.local/opt/chattarina \
    || { echo "chattarina does not seem to be installed. First run it with the --install flag:\n  chattarina --install"; exit 1; }


# Actually run it!
source venv/bin/activate
python3 chattarina.py